### ISSUE TITLE
Not able to publish changes made in particular session

### ISSUE THREAD

**Issue by chintansbhut** [Rmauldin/matterport#1]
Is there any way, using which we can publish /persist changes made in a session? I have added new tags / updated a few tags and removed tags. All these operations are successful and I am able to visualize results on the scan until I refresh my window. 
Can you please help me figure out the way, using which I can able to solve the above issue?

**Comment by Rmauldin** [comment]
The Matterport SDK can't make changes back the the Matterport platform. Changes made with the SDK are only persistent to the current web session.

This article contains more information about it - https://support.matterport.com/hc/en-us/articles/360061477754-Getting-Started-With-The-SDK
